POST http://localhost:9090/auth
Content-Type: application/json

{
  "authKey": "767vg0s4",
  "type": "user"
}

###
POST https://de157b9e2a59.ngrok.io/auth
Content-Type: application/json

{
  "authKey": "767vg0s4",
  "type": "user"
}

###

POST http://96231f4c7749.ngrok.io/auth
Content-Type: application/json

{
  "authKey": "767vg0s4",
  "type": "user"
}

###

POST http://localhost:9090/runner/start

###

GET http://localhost:9090/user/followup
Content-Type: application/json

{
  "date": "2020-11-21"
}

### 
GET http://localhost:9090/user/followup-today

###
GET http://localhost:9090/logs/all