POST http://localhost:9090/auth
Content-Type: application/json

{
  "authKey": "767vg0s4",
  "type": "user"
}

### 

GET https://api.genderize.io/?name=teodor

### 
GET  https://5e3b4a1aad2b.ngrok.io/logs

### 
GET https://5e3b4a1aad2b.ngrok.io/runner/stop

###
GET https://5e3b4a1aad2b.ngrok.io/runner/status

###
GET https://5e3b4a1aad2b.ngrok.io/update

###
GET https://de157b9e2a59.ngrok.io/runner/status

###
GET http://5e3b4a1aad2b.ngrok.io/runner/stop

###
POST https://de157b9e2a59.ngrok.io/auth
Content-Type: application/json

{
  "authKey": "767vg0s4",
  "type": "user"
}

###

POST http://96231f4c7749.ngrok.io/auth
Content-Type: application/json

{
  "authKey": "767vg0s4",
  "type": "user"
}