POST http://localhost:9090/auth
Content-Type: application/json

{
  "authKey": "767vg0s4",
  "type": "user"
}

### 

GET https://api.genderize.io/?name=teodor

### 
GET  http://localhost:9090/logs

### 
GET http://localhost:9090/runner/stop