require('dotenv').config()
const express = require('express')
const { json } = require('body-parser')
const cors = require('cors')
const server = require('./api/server')
const registerRoutes = require('./api/registerRoutes')
const connectDB = require('./api/connectDB')

const app = express()
app.use(json())
app.use(cors({ origin: true }))
registerRoutes(app)
connectDB()
server(app)